version: '3'

volumes:
  mysql-db:
    driver: local

services:
  app:
    container_name: app
    build: ./app
    command: php /var/www/artisan serve --host 0.0.0.0 --port 80
    ports:
    - 80:80
    volumes:
    - ../src:/var/www
    depends_on:
    - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - mysql-db:/var/lib/mysql
    - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./mysql/initdb:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306